"""
Schema 模块

导出所有数据结构定义
"""

from .roles_schema import (
    ActionType,
    CampType,
    RoleType,
    NightActionResult,
    WerewolfKillResult,
    ProphetCheckResult,
    WitchSaveResult,
    WitchPoisonResult,
    HunterShootResult,
    GuardResult,
    NoNightActionResult,
    DayActionResult,
    VoteResult,
    SpeakResult,
    RevealResult,
    NoDayActionResult,
    PublicInfo,
    PrivateInfo,
    RoleStatus,
    PlayerState,
    GamePhaseState,
    DeathReason,
    Ability,
)

from .game_logger_schema import (
    GameMode,
    GameSettings,
    GameInfo,
    PlayerInfo,
    DeathRecord,
    NightEventType,
    WerewolfKillEvent,
    ProphetCheckEvent,
    WitchSaveEvent,
    WitchPoisonEvent,
    GuardGuardEvent,
    HunterShootEvent,
    NoDeathEvent,
    NightResult,
    DayEventType,
    SpeechEvent,
    VoteEvent,
    ExileEvent,
    RevealEvent,
    AnnouncementEvent,
    DayResult,
    DayRecord,
    Winner,
    PlayerResult,
    GameResult,
    GameRecord,
    EventLogEntry,
)

from .api_schema import (
    CreateGameRequest,
    CreateGameResponse,
    CreateAgentsRequest,
    GameInfoResponse,
    NightResultResponse,
    DayResultResponse,
    GameRecordResponse,
    ErrorResponse,
)

__all__ = [
    # roles_schema
    "ActionType",
    "CampType",
    "RoleType",
    "NightActionResult",
    "WerewolfKillResult",
    "ProphetCheckResult",
    "WitchSaveResult",
    "WitchPoisonResult",
    "HunterShootResult",
    "GuardResult",
    "NoNightActionResult",
    "DayActionResult",
    "VoteResult",
    "SpeakResult",
    "RevealResult",
    "NoDayActionResult",
    "PublicInfo",
    "PrivateInfo",
    "RoleStatus",
    "PlayerState",
    "GamePhaseState",
    "DeathReason",
    "Ability",
    # game_logger_schema
    "GameMode",
    "GameSettings",
    "GameInfo",
    "PlayerInfo",
    "DeathRecord",
    "NightEventType",
    "WerewolfKillEvent",
    "ProphetCheckEvent",
    "WitchSaveEvent",
    "WitchPoisonEvent",
    "GuardGuardEvent",
    "HunterShootEvent",
    "NoDeathEvent",
    "NightResult",
    "DayEventType",
    "SpeechEvent",
    "VoteEvent",
    "ExileEvent",
    "RevealEvent",
    "AnnouncementEvent",
    "DayResult",
    "DayRecord",
    "Winner",
    "PlayerResult",
    "GameResult",
    "GameRecord",
    "EventLogEntry",
    # api_schema
    "CreateGameRequest",
    "CreateGameResponse",
    "CreateAgentsRequest",
    "GameInfoResponse",
    "NightResultResponse",
    "DayResultResponse",
    "GameRecordResponse",
    "ErrorResponse",
]
